# stages: [Build, Deploy]
stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo "Building function..."
              # Your build commands here (e.g., npm install, build, package)
            displayName: "Build Function"

  - stage: Deploy
    dependsOn:
      - Build
    jobs:
      - job: Deploy
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DownloadSecureFile@1
            displayName: "Download Service Account Key"
            inputs:
              secureFile: serviceAccountKey

          - task: Bash@3
            displayName: "Deploy Cloud Function"
            inputs:
              targetType: 'inline'
              script: |
                # Authenticate with service account key
                gcloud auth activate-service-account --key-file $(Agent.TempDirectory)/serviceAccountKey.json

                # Set the project (optional if already set)
                gcloud config set project compute-iam-test

                # Deploy the function
                gcloud functions deploy myFunction \
                  --region=us-central1 \
                  --source=. \
                  --runtime=python311 \
                  --trigger-http \
                  --allow-unauthenticated \
                  --entry-point=my_entry_point \
                  --service-account=cloud-function-deployer@compute-iam-test.iam.gserviceaccount.com \
                  --quiet
        displayName: "Deploy Cloud Function"