Example Pipeline YAML:
Code
 
# stages: [Build, Deploy]
stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo "Building function..."
              # Your build commands here (e.g., npm install, build, package)
            displayName: "Build Function"
  - stage: Deploy
    dependsOn:
      - Build
    jobs:
      - job: Deploy
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DownloadSecureFile@1
            displayName: "Download Service Account Key"
            inputs:
              secureFile: serviceAccountKey
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                gcloud functions deploy <function-name> \
                  --region=$(GCP_REGION) \
                  --source=. \
                  --runtime=<runtime> \
                  --trigger-http \
                  --allow-unauthenticated \
                  --entry-point=<entryPoint> \
                  --quiet
      
            displayName: "Deploy Function"