# stages: [Build, Deploy]
stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo "Building function..."
              # Your build commands here (e.g., npm install, build, package)
            displayName: "Build Function"

  - stage: Deploy
    dependsOn:
      - Build
    jobs:
      - job: Deploy
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DownloadSecureFile@1
            displayName: "Download Service Account Key"
            inputs:
              secureFile: serviceAccountKey

          - task: Bash@3
            displayName: "Deploy Cloud Function"
            inputs:
              targetType: 'inline'
              script: |
                # Authenticate with service account key
                gcloud auth activate-service-account --key-file "$(Agent.TempDirectory)/compute-iam-test-c777ed5d2926.json"

                # Set the project
                gcloud config set project compute-iam-test

                # Store working directory safely
                SOURCE_DIR="$(System.DefaultWorkingDirectory)"

                echo "Deploying from source: $SOURCE_DIR"

                # Deploy the function
                gcloud functions deploy myFunctiondemo \
                  --region=us-central1 \
                  --source="$SOURCE_DIR" \
                  --runtime=python311 \
                  --trigger-http \
                  --allow-unauthenticated \
                  --entry-point=my_entry_point \
                  --service-account=cloud-function-deployer@compute-iam-test.iam.gserviceaccount.com \
                  --quiet